/**
 * 演示种子数据 — 首次访问时自动灌入 localStorage
 */
import type { CustomerRecord } from '../components/CustomerBoard/constants'

const now = new Date()
const daysAgo = (n: number) =>
  new Date(now.getTime() - n * 24 * 60 * 60 * 1000).toISOString()

export const SEED_CUSTOMERS: Omit<CustomerRecord, 'id'>[] = [
  {
    pro_account_id: 'DEMO_00001',
    customer_source: '代理商推荐',
    pro_account_name: 'ExampleCorp Beauty',
    country_region: '日本',
    industry_l1: '美妆个护',
    industry_l2: '护肤',
    channel_manager: 'Alice',
    current_status: '已开通',
    block_type: '无卡点',
    follow_up_note: '客户已完成开通，本周开始首轮投放',
    next_action: '关注首周ROI表现',
    last_follow_up_at: daysAgo(1),
    chat_screenshots: null,
    remark: '重点客户',
    source_type: '表格上传',
    creator: 'Demo User',
    author_name: 'Demo User',
    created_at: daysAgo(20),
    updated_at: daysAgo(1),
  },
  {
    pro_account_id: 'DEMO_00002',
    customer_source: '客户主动咨询',
    pro_account_name: 'SampleBrand Fashion',
    country_region: '韩国',
    industry_l1: '服饰鞋帽',
    industry_l2: '女装',
    channel_manager: 'Bob',
    current_status: '待客户补充材料',
    block_type: '材料缺失',
    follow_up_note: '客户已确认开通意向，等待提供营业执照翻译件',
    next_action: '下周一前催单营业执照',
    last_follow_up_at: daysAgo(2),
    chat_screenshots: null,
    remark: '',
    source_type: '手动新增',
    creator: 'Demo User',
    author_name: 'Demo User',
    created_at: daysAgo(15),
    updated_at: daysAgo(2),
  },
  {
    pro_account_id: 'DEMO_00003',
    customer_source: 'AM推荐',
    pro_account_name: 'DemoStore Home',
    country_region: '美国',
    industry_l1: '家居生活',
    industry_l2: '家纺',
    channel_manager: 'Alice',
    current_status: '跟进中',
    block_type: '客户未回复',
    follow_up_note: '首次触达客户，已介绍开通流程',
    next_action: '3天后二次跟进',
    last_follow_up_at: daysAgo(3),
    chat_screenshots: null,
    remark: '客户对成本敏感',
    source_type: '手动新增',
    creator: 'Demo User',
    author_name: 'Demo User',
    created_at: daysAgo(5),
    updated_at: daysAgo(3),
  },
  {
    pro_account_id: 'DEMO_00004',
    customer_source: '存量迁移',
    pro_account_name: 'TrialCo Snacks',
    country_region: '日本',
    industry_l1: '食品饮料',
    industry_l2: '休闲零食',
    channel_manager: 'Cathy',
    current_status: '审核卡住',
    block_type: '资质卡审',
    follow_up_note: '类目资质审核未通过，正在协调补充食品准入证',
    next_action: '联系类目审核同事加急',
    last_follow_up_at: daysAgo(4),
    chat_screenshots: null,
    remark: '需要类目侧支持',
    source_type: '表格上传',
    creator: 'Demo User',
    author_name: 'Demo User',
    created_at: daysAgo(25),
    updated_at: daysAgo(4),
  },
  {
    pro_account_id: 'DEMO_00005',
    customer_source: '代理商推荐',
    pro_account_name: 'SampleBrand Tech',
    country_region: '新加坡',
    industry_l1: '3C数码',
    industry_l2: '智能穿戴',
    channel_manager: 'David',
    current_status: '待内部审核',
    block_type: '内部审核待处理',
    follow_up_note: '材料已齐，等待类目审核',
    next_action: '预计2个工作日内出结果',
    last_follow_up_at: daysAgo(2),
    chat_screenshots: null,
    remark: '',
    source_type: '手动新增',
    creator: 'Demo User',
    author_name: 'Demo User',
    created_at: daysAgo(8),
    updated_at: daysAgo(2),
  },
  {
    pro_account_id: 'DEMO_00006',
    customer_source: '客户主动咨询',
    pro_account_name: 'ExampleCorp Toys',
    country_region: '澳大利亚',
    industry_l1: '母婴用品',
    industry_l2: '玩具',
    channel_manager: 'Bob',
    current_status: '已触达',
    block_type: null,
    follow_up_note: '首次沟通，客户表达开通意向',
    next_action: '发送开通材料清单',
    last_follow_up_at: daysAgo(1),
    chat_screenshots: null,
    remark: '',
    source_type: '手动新增',
    creator: 'Demo User',
    author_name: 'Demo User',
    created_at: daysAgo(2),
    updated_at: daysAgo(1),
  },
  {
    pro_account_id: 'DEMO_00007',
    customer_source: 'AM推荐',
    pro_account_name: 'DemoStore Beauty',
    country_region: '马来西亚',
    industry_l1: '美妆个护',
    industry_l2: '彩妆',
    channel_manager: 'Cathy',
    current_status: '未跟进',
    block_type: null,
    follow_up_note: null,
    next_action: '本周内首次触达',
    last_follow_up_at: null,
    chat_screenshots: null,
    remark: '新分配的线索',
    source_type: '表格上传',
    creator: 'Demo User',
    author_name: 'Demo User',
    created_at: daysAgo(1),
    updated_at: daysAgo(1),
  },
  {
    pro_account_id: 'DEMO_00008',
    customer_source: '代理商推荐',
    pro_account_name: 'TrialCo Outdoor',
    country_region: '美国',
    industry_l1: '运动户外',
    industry_l2: '户外装备',
    channel_manager: 'Alice',
    current_status: '已开通',
    block_type: '无卡点',
    follow_up_note: '已完成开通并投放首笔预算',
    next_action: '本月复盘投放效果',
    last_follow_up_at: daysAgo(6),
    chat_screenshots: null,
    remark: '',
    source_type: '手动新增',
    creator: 'Demo User',
    author_name: 'Demo User',
    created_at: daysAgo(30),
    updated_at: daysAgo(6),
  },
  {
    pro_account_id: 'DEMO_00009',
    customer_source: '存量迁移',
    pro_account_name: 'SampleBrand Pet',
    country_region: '日本',
    industry_l1: '宠物用品',
    industry_l2: '宠物食品',
    channel_manager: 'David',
    current_status: '暂停推进',
    block_type: '其他',
    follow_up_note: '客户内部调整，暂时不推进',
    next_action: '两个月后再触达',
    last_follow_up_at: daysAgo(15),
    chat_screenshots: null,
    remark: '客户在调整业务方向',
    source_type: '手动新增',
    creator: 'Demo User',
    author_name: 'Demo User',
    created_at: daysAgo(45),
    updated_at: daysAgo(15),
  },
  {
    pro_account_id: 'DEMO_00010',
    customer_source: '客户主动咨询',
    pro_account_name: 'ExampleCorp Books',
    country_region: '英国',
    industry_l1: '图书文娱',
    industry_l2: '图书',
    channel_manager: 'Bob',
    current_status: '无效线索',
    block_type: '行业准入限制',
    follow_up_note: '客户所在类目暂不支持开通',
    next_action: '标记为无效并关闭',
    last_follow_up_at: daysAgo(10),
    chat_screenshots: null,
    remark: '类目限制',
    source_type: '手动新增',
    creator: 'Demo User',
    author_name: 'Demo User',
    created_at: daysAgo(12),
    updated_at: daysAgo(10),
  },
  {
    pro_account_id: 'DEMO_00011',
    customer_source: 'AM推荐',
    pro_account_name: 'DemoStore Sports',
    country_region: '德国',
    industry_l1: '运动户外',
    industry_l2: '运动服饰',
    channel_manager: 'Cathy',
    current_status: '跟进中',
    block_type: '渠道经理待跟进',
    follow_up_note: '客户已同意开通，等待渠道经理走开户流程',
    next_action: '本周内走通开户',
    last_follow_up_at: daysAgo(1),
    chat_screenshots: null,
    remark: '',
    source_type: '表格上传',
    creator: 'Demo User',
    author_name: 'Demo User',
    created_at: daysAgo(10),
    updated_at: daysAgo(1),
  },
  {
    pro_account_id: 'DEMO_00012',
    customer_source: '代理商推荐',
    pro_account_name: 'TrialCo Kids',
    country_region: '法国',
    industry_l1: '母婴用品',
    industry_l2: '童装',
    channel_manager: 'David',
    current_status: '待客户补充材料',
    block_type: '材料缺失',
    follow_up_note: '缺主体授权书',
    next_action: '客户明天提供',
    last_follow_up_at: daysAgo(1),
    chat_screenshots: null,
    remark: '',
    source_type: '手动新增',
    creator: 'Demo User',
    author_name: 'Demo User',
    created_at: daysAgo(4),
    updated_at: daysAgo(1),
  },
  {
    pro_account_id: 'DEMO_00013',
    customer_source: '客户主动咨询',
    pro_account_name: 'ExampleCorp Kitchen',
    country_region: '意大利',
    industry_l1: '家居生活',
    industry_l2: '厨具',
    channel_manager: 'Alice',
    current_status: '审核卡住',
    block_type: '专业号认证问题',
    follow_up_note: '专业号认证信息与营业执照不一致',
    next_action: '客户重新提交认证',
    last_follow_up_at: daysAgo(9),
    chat_screenshots: null,
    remark: '涉及多地区主体',
    source_type: '手动新增',
    creator: 'Demo User',
    author_name: 'Demo User',
    created_at: daysAgo(20),
    updated_at: daysAgo(9),
  },
  {
    pro_account_id: 'DEMO_00014',
    customer_source: '存量迁移',
    pro_account_name: 'SampleBrand Wine',
    country_region: '西班牙',
    industry_l1: '食品饮料',
    industry_l2: '酒水',
    channel_manager: 'Bob',
    current_status: '已开通',
    block_type: '无卡点',
    follow_up_note: '开通完成，首月ROI良好',
    next_action: '拓展二级类目',
    last_follow_up_at: daysAgo(5),
    chat_screenshots: null,
    remark: '',
    source_type: '表格上传',
    creator: 'Demo User',
    author_name: 'Demo User',
    created_at: daysAgo(60),
    updated_at: daysAgo(5),
  },
  {
    pro_account_id: 'DEMO_00015',
    customer_source: 'AM推荐',
    pro_account_name: 'DemoStore Baby',
    country_region: '加拿大',
    industry_l1: '母婴用品',
    industry_l2: '孕产用品',
    channel_manager: 'Cathy',
    current_status: '待内部审核',
    block_type: '聚光开户问题',
    follow_up_note: '聚光账户开户审核中',
    next_action: '跟进开户结果',
    last_follow_up_at: daysAgo(3),
    chat_screenshots: null,
    remark: '',
    source_type: '手动新增',
    creator: 'Demo User',
    author_name: 'Demo User',
    created_at: daysAgo(7),
    updated_at: daysAgo(3),
  },
  {
    pro_account_id: 'DEMO_00016',
    customer_source: '代理商推荐',
    pro_account_name: 'ExampleCorp Cycle',
    country_region: '荷兰',
    industry_l1: '运动户外',
    industry_l2: '自行车',
    channel_manager: 'David',
    current_status: '跟进中',
    block_type: null,
    follow_up_note: '客户在评估投放预算',
    next_action: '本周内确认预算规模',
    last_follow_up_at: daysAgo(2),
    chat_screenshots: null,
    remark: '',
    source_type: '手动新增',
    creator: 'Demo User',
    author_name: 'Demo User',
    created_at: daysAgo(6),
    updated_at: daysAgo(2),
  },
  {
    pro_account_id: 'DEMO_00017',
    customer_source: '客户主动咨询',
    pro_account_name: 'TrialCo Skin',
    country_region: '韩国',
    industry_l1: '美妆个护',
    industry_l2: '面膜',
    channel_manager: 'Alice',
    current_status: '已开通',
    block_type: '无卡点',
    follow_up_note: '已开通并投放，效果超预期',
    next_action: '追加预算方案',
    last_follow_up_at: daysAgo(2),
    chat_screenshots: null,
    remark: '重点客户',
    source_type: '手动新增',
    creator: 'Demo User',
    author_name: 'Demo User',
    created_at: daysAgo(40),
    updated_at: daysAgo(2),
  },
  {
    pro_account_id: 'DEMO_00018',
    customer_source: 'AM推荐',
    pro_account_name: 'SampleBrand Deco',
    country_region: '美国',
    industry_l1: '家居生活',
    industry_l2: '家饰',
    channel_manager: 'Bob',
    current_status: '未跟进',
    block_type: null,
    follow_up_note: null,
    next_action: null,
    last_follow_up_at: null,
    chat_screenshots: null,
    remark: '新分配的线索',
    source_type: '表格上传',
    creator: 'Demo User',
    author_name: 'Demo User',
    created_at: daysAgo(2),
    updated_at: daysAgo(2),
  },
  {
    pro_account_id: 'DEMO_00019',
    customer_source: '存量迁移',
    pro_account_name: 'DemoStore Coffee',
    country_region: '澳大利亚',
    industry_l1: '食品饮料',
    industry_l2: '咖啡',
    channel_manager: 'Cathy',
    current_status: '跟进中',
    block_type: '客户未回复',
    follow_up_note: '首次电话未接通，已发送邮件',
    next_action: '3天后再次电话跟进',
    last_follow_up_at: daysAgo(10),
    chat_screenshots: null,
    remark: '',
    source_type: '手动新增',
    creator: 'Demo User',
    author_name: 'Demo User',
    created_at: daysAgo(11),
    updated_at: daysAgo(10),
  },
  {
    pro_account_id: 'DEMO_00020',
    customer_source: '代理商推荐',
    pro_account_name: 'ExampleCorp Wear',
    country_region: '日本',
    industry_l1: '服饰鞋帽',
    industry_l2: '男装',
    channel_manager: 'David',
    current_status: '已触达',
    block_type: null,
    follow_up_note: '客户表达开通兴趣，需要更多资料',
    next_action: '发送开通指南和成功案例',
    last_follow_up_at: daysAgo(1),
    chat_screenshots: null,
    remark: '',
    source_type: '手动新增',
    creator: 'Demo User',
    author_name: 'Demo User',
    created_at: daysAgo(3),
    updated_at: daysAgo(1),
  },
]
